// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViewModelExtended.Model;

namespace ViewModelExtended.Migrations
{
    [DbContext(typeof(ViewModelExtended.Model.DbContext))]
    [Migration("20220613030409_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24");

            modelBuilder.Entity("ViewModelExtended.Model.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("ViewModelExtended.Model.GroupItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimestampId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GroupItems");
                });

            modelBuilder.Entity("ViewModelExtended.Model.GroupListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimestampId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GroupListItems");
                });

            modelBuilder.Entity("ViewModelExtended.Model.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NextId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PreviousId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("ViewModelExtended.Model.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("ViewModelExtended.Model.NoteListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimestampId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NoteListItems");
                });

            modelBuilder.Entity("ViewModelExtended.Model.Timestamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AutoModified")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserCreated")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserIndexed")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserModified")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Timestamps");
                });
#pragma warning restore 612, 618
        }
    }
}
